"""Keyword taxonomies used by the deterministic exception classifier."""

from app.models import Category


CATEGORY_KEYWORDS: dict[Category, tuple[str, ...]] = {
    Category.VEHICLE_ISSUE: (
        # English
        "breakdown",
        "engine problem",
        "engine issue",
        "car problem",
        "vehicle problem",
        "flat tire",
        "puncture",
        "tire",
        "tyre",
        "battery",
        "accident",
        "vehicle stopped",
        "car stopped",

        # French commonly used in Tunisia
        "panne",
        "panne voiture",
        "panne camion",
        "problème voiture",
        "probleme voiture",
        "problème moteur",
        "probleme moteur",
        "moteur",
        "pneu",
        "pneu crevé",
        "pneu creve",
        "batterie",
        "accident",
        "camion bloqué",
        "camion bloque",
        "voiture bloquée",
        "voiture bloquee",

        # Tunisian Arabic / Arabizi
        "kharban",
        "5arban",
        "5arbène",
        "5arben",
        "kharbena",
        "moteur kharban",
        "moteur ma yekhdemch",
        "el moteur ma yekhdemch",
        "el karhba kharbena",
        "karhba kharbena",
        "el camion kharban",
        "el camion wa9af",
        "el karhba wa9fa",
        "karhba wa9fa",
        "wa9af",
        "wa9fa",
        "ma yemchich",
        "ma temchich",
        "ma yekhdemch",
        "ma tekhdemch",
        "batriya",
        "batterie fargha",
        "batterie fergha",
        "pneu mawjeb",
        "pneu mhabbot",
        "pneu mthaqeb",
        "pneu thaqeb",
        "roue mhabbta",
        "rouda mhabbta",
        "crevé",
        "creve",
        "mthaqeb",
        "thaqeb",
        "moteur skhoun",
        "el moteur skhoun",
        "sokhna fil moteur",
        "karhba t3attlet",
        "el karhba t3attlet",
        "el camion t3attel",
        "t3attel",
        "t3atlet",
        "t3atla",
        "3atlet",
        "3atla",
        "3atla fi tri9",
        "3atla fil karhba",
        "khsara",
        "khasra",
        "ksar",
        "ma3adech temchi",
        "ma3adech yemchi",
        "ma3adech yekhdem",
        "wa9fet fil tri9",
        "wa9ef fil tri9",

        # Tunisian Arabic script
        "خربان",
        "خربانة",
        "الموتور خربان",
        "الموتور ما يخدمش",
        "الكرهبة خربانة",
        "الكراهب خربانة",
        "الكاميو خربان",
        "الكاميو واقف",
        "الكرهبة واقفة",
        "واقف",
        "واقفة",
        "ما يمشيش",
        "ما تمشيش",
        "ما يخدمش",
        "ما تخدمش",
        "بطارية",
        "البطارية فارغة",
        "بونيو مهبّط",
        "بونيو مثقّب",
        "رويدة مهبّطة",
        "تعطلت",
        "عطلت",
        "عطلة",
        "عطلة في الكرهبة",
        "خسارة",
        "وقفت في الطريق",
    ),

    Category.CUSTOMER_ABSENT: (
        # English
        "absent",
        "not home",
        "nobody home",
        "no answer",
        "no response",
        "customer unavailable",
        "customer not available",
        "customer is out",
        "not there",
        "could not reach customer",
        "couldn't reach customer",
        "phone unanswered",

        # French commonly used in Tunisia
        "client absent",
        "client indisponible",
        "client injoignable",
        "personne à la maison",
        "personne a la maison",
        "pas de réponse",
        "pas de reponse",
        "ne répond pas",
        "ne repond pas",
        "client sorti",
        "client n'est pas là",
        "client n'est pas la",

        # Tunisian Arabic / Arabizi
        "makanech",
        "ma famech",
        "ma famech 7ad",
        "ma famech 7ad fel dar",
        "ma famech 7ad fi dar",
        "ma l9inach 7ad",
        "mal9inach 7ad",
        "ma l9itech",
        "mal9itech",
        "ma l9inéhch",
        "ma7adech",
        "ma7adhech",
        "ma7ad ch",
        "ma jawebch",
        "ma jawbnech",
        "ma raddch",
        "ma rodech",
        "ma yroddech",
        "ma yjewbch",
        "ma yjibch",
        "sakket",
        "telifounou sakket",
        "telephone sakket",
        "ma yjewbch fil tel",
        "raho kharej",
        "raha 5arja",
        "kharej",
        "5arej",
        "5arja",
        "mouch mawjoud",
        "mouch mawjouda",
        "mouch fil dar",
        "mouch fel dar",
        "mouch houni",
        "ma l9inehch fil dar",
        "ma l9inehech",
        "ma l9inech el client",
        "el client kharej",

        # Tunisian Arabic script
        "ما كانش",
        "ما فماش",
        "ما فماش حد",
        "ما فماش حد في الدار",
        "ما لقيناش حد",
        "ما لقيتش",
        "ما لقيناهش",
        "ما جاوبش",
        "ما جاوبنيش",
        "ما ردش",
        "ما يجاوبش",
        "ساكت",
        "تليفونو ساكت",
        "راهو خارج",
        "راهي خارجة",
        "موش موجود",
        "موش موجودة",
        "موش في الدار",
        "موش هوني",
        "الكليان خارج",
        "الحريف خارج",
    ),

    Category.WEATHER: (
        # English
        "rain",
        "heavy rain",
        "storm",
        "thunderstorm",
        "flood",
        "flooding",
        "bad weather",
        "weather problem",
        "snow",
        "wind",
        "strong wind",
        "road blocked by weather",
        "road closed",

        # French commonly used in Tunisia
        "pluie",
        "forte pluie",
        "orage",
        "inondation",
        "inondations",
        "mauvais temps",
        "neige",
        "vent fort",
        "route bloquée",
        "route bloquee",
        "route fermée",
        "route fermee",

        # Tunisian Arabic / Arabizi
        "chta",
        "cheta",
        "cḥéta",
        "matar",
        "matar barcha",
        "matar 9wi",
        "matar 9awi",
        "rih",
        "ri7",
        "ri7 9wiya",
        "rih 9wiya",
        "ri7 9awia",
        "3ajja",
        "ajja",
        "storm",
        "sila",
        "siyel",
        "fayadan",
        "fayadhan",
        "feydhane",
        "el bhar fayed",
        "tri9 masdouda",
        "tri9 msakra",
        "tri9 msakra bel matar",
        "twaggef et-tri9",
        "et-tri9 wa9fa",
        "et-tri9 msakra",
        "talj",
        "bard barcha",
        "s9i3",
        "s9i3 barcha",
        "dhoch",
        "dhoch barcha",

        # Tunisian Arabic script
        "شتا",
        "شتى",
        "مطر",
        "مطر برشة",
        "مطر قوي",
        "ريح",
        "ريح قوية",
        "عجاج",
        "سيل",
        "سيول",
        "فيضان",
        "الطريق مسدودة",
        "الطريق مسكّرة",
        "الطريق واقفة",
        "الطريق مسكّرة بالمطر",
        "ثلج",
        "برد برشة",
        "صقيع",
    ),
}


HIGH_SEVERITY_KEYWORDS = (
    # English
    "urgent",
    "delayed",
    "delay",
    "blocked",
    "major",
    "serious",
    "late",
    "very late",
    "long delay",
    "cannot continue",
    "unable to deliver",

    # French
    "urgent",
    "retard",
    "en retard",
    "gros retard",
    "bloqué",
    "bloque",
    "grave",
    "problème sérieux",
    "probleme serieux",
    "livraison impossible",

    # Tunisian Arabic / Arabizi
    "ta5ir",
    "ta5ir barcha",
    "t5ir",
    "mte5er",
    "mte5ra",
    "mesta3jel",
    "mousta3jel",
    "mosta3jel",
    "3ajel",
    "3ajla",
    "mouch normal",
    "moch normal",
    "mochkla kbira",
    "mochkel kbira",
    "mochkla kbir",
    "ma najamch nkamel",
    "ma najamch nousel",
    "ma najamtch nsallem",
    "wa9ef",
    "msakker",
    "msakra",
    "blocked",
    "kol chay wa9ef",

    # Tunisian Arabic script
    "تأخير",
    "متأخر",
    "متأخرة",
    "تأخير برشة",
    "مستعجل",
    "عاجل",
    "عاجلة",
    "مشكلة كبيرة",
    "موش عادي",
    "ما نجمش نكمل",
    "ما نجمتش نسلم",
    "واقف",
    "مسكّر",
    "مسكّرة",
)


CRITICAL_SEVERITY_KEYWORDS = (
    # English
    "critical",
    "emergency",
    "injury",
    "injured",
    "danger",
    "dangerous",
    "severe",
    "total loss",
    "life threatening",
    "medical emergency",
    "police",
    "ambulance",

    # French
    "critique",
    "urgence",
    "blessé",
    "blesse",
    "blessure",
    "danger",
    "dangereux",
    "grave",
    "perte totale",
    "police",
    "ambulance",

    # Tunisian Arabic / Arabizi
    "5atir",
    "5atira",
    "jri7",
    "jriha",
    "jraya",
    "isaba",
    "issaba",
    "7adeth",
    "7adtha",
    "7adeth kbira",
    "accident kbira",
    "mochkla 5atira",
    "mouchkla 5atira",
    "khatra",
    "khatar",
    "faza3a",
    "faza3",
    "mousta3jla barcha",
    "taleb ambulance",
    "taleb police",
    "dam",
    "yodrob fil dam",
    "ma yeta7ammelch",

    # Tunisian Arabic script
    "خطر",
    "خطيرة",
    "جريح",
    "جريحة",
    "إصابة",
    "حادث",
    "حادثة",
    "حادث كبير",
    "حادث خطير",
    "مشكلة خطيرة",
    "طارئ",
    "حالة طارئة",
    "إسعاف",
    "بوليس",
    "دم",
)
