"""Keyword taxonomies used by the deterministic exception classifier."""

from app.models import Category


CATEGORY_KEYWORDS: dict[Category, tuple[str, ...]] = {
    Category.VEHICLE_ISSUE: (
        # English
        "breakdown",
        "engine problem",
        "engine issue",
        "car problem",
        "vehicle problem",
        "flat tire",
        "puncture",
        "tire",
        "tyre",
        "battery",
        "accident",
        "vehicle stopped",
        "car stopped",

        # French commonly used in Tunisia
        "panne",
        "panne voiture",
        "panne camion",
        "problème voiture",
        "probleme voiture",
        "problème moteur",
        "probleme moteur",
        "moteur",
        "pneu",
        "pneu crevé",
        "pneu creve",
        "batterie",
        "accident",
        "camion bloqué",
        "camion bloque",
        "voiture bloquée",
        "voiture bloquee",

        # Tunisian Arabic / Arabizi
        "kharban",
        "5arban",
        "5arbène",
        "5arben",
        "kharbena",
        "moteur kharban",
        "moteur ma yekhdemch",
        "el moteur ma yekhdemch",
        "el karhba kharbena",
        "karhba kharbena",
        "el camion kharban",
        "el camion wa9af",
        "el karhba wa9fa",
        "karhba wa9fa",
        "wa9af",
        "wa9fa",
        "ma yemchich",
        "ma temchich",
        "ma yekhdemch",
        "ma tekhdemch",
        "batriya",
        "batterie fargha",
        "batterie fergha",
        "pneu mawjeb",
        "pneu mhabbot",
        "pneu mthaqeb",
        "pneu thaqeb",
        "roue mhabbta",
        "rouda mhabbta",
        "crevé",
        "creve",
        "mthaqeb",
        "thaqeb",
        "moteur skhoun",
        "el moteur skhoun",
        "sokhna fil moteur",
        "karhba t3attlet",
        "el karhba t3attlet",
        "el camion t3attel",
        "t3attel",
        "t3atlet",
        "t3atla",
        "3atlet",
        "3atla",
        "3atla fi tri9",
        "3atla fil karhba",
        "khsara",
        "khasra",
        "ksar",
        "ma3adech temchi",
        "ma3adech yemchi",
        "ma3adech yekhdem",
        "wa9fet fil tri9",
        "wa9ef fil tri9",

        # Tunisian Arabic script
        "خربان",
        "خربانة",
        "الموتور خربان",
        "الموتور ما يخدمش",
        "الكرهبة خربانة",
        "الكراهب خربانة",
        "الكاميو خربان",
        "الكاميو واقف",
        "الكرهبة واقفة",
        "واقف",
        "واقفة",
        "ما يمشيش",
        "ما تمشيش",
        "ما يخدمش",
        "ما تخدمش",
        "بطارية",
        "البطارية فارغة",
        "بونيو مهبّط",
        "بونيو مثقّب",
        "رويدة مهبّطة",
        "تعطلت",
        "عطلت",
        "عطلة",
        "عطلة في الكرهبة",
        "خسارة",
        "وقفت في الطريق",
    ),

    Category.CUSTOMER_ABSENT: (
        # English
        "absent",
        "not home",
        "nobody home",
        "no answer",
        "no response",
        "customer unavailable",
        "customer not available",
        "customer is out",
        "not there",
        "could not reach customer",
        "couldn't reach customer",
        "phone unanswered",

        # French commonly used in Tunisia
        "client absent",
        "client indisponible",
        "client injoignable",
        "personne à la maison",
        "personne a la maison",
        "pas de réponse",
        "pas de reponse",
        "ne répond pas",
        "ne repond pas",
        "client sorti",
        "client n'est pas là",
        "client n'est pas la",

        # Tunisian Arabic / Arabizi
        "makanech",
        "ma famech",
        "ma famech 7ad",
        "ma famech 7ad fel dar",
        "ma famech 7ad fi dar",
        "ma l9inach 7ad",
        "mal9inach 7ad",
        "ma l9itech",
        "mal9itech",
        "ma l9inéhch",
        "ma7adech",
        "ma7adhech",
        "ma7ad ch",
        "ma jawebch",
        "ma jawbnech",
        "ma raddch",
        "ma rodech",
        "ma yroddech",
        "ma yjewbch",
        "ma yjibch",
        "sakket",
        "telifounou sakket",
        "telephone sakket",
        "ma yjewbch fil tel",
        "raho kharej",
        "raha 5arja",
        "kharej",
        "5arej",
        "5arja",
        "mouch mawjoud",
        "mouch mawjouda",
        "mouch fil dar",
        "mouch fel dar",
        "mouch houni",
        "ma l9inehch fil dar",
        "ma l9inehech",
        "ma l9inech el client",
        "el client kharej",

        # Tunisian Arabic script
        "ما كانش",
        "ما فماش",
        "ما فماش حد",
        "ما فماش حد في الدار",
        "ما لقيناش حد",
        "ما لقيتش",
        "ما لقيناهش",
        "ما جاوبش",
        "ما جاوبنيش",
        "ما ردش",
        "ما يجاوبش",
        "ساكت",
        "تليفونو ساكت",
        "راهو خارج",
        "راهي خارجة",
        "موش موجود",
        "موش موجودة",
        "موش في الدار",
        "موش هوني",
        "الكليان خارج",
        "الحريف خارج",
    ),

    Category.WEATHER: (
        # English
        "rain",
        "heavy rain",
        "storm",
        "thunderstorm",
        "flood",
        "flooding",
        "bad weather",
        "weather problem",
        "snow",
        "wind",
        "strong wind",
        "road blocked by weather",
        "road closed",

        # French commonly used in Tunisia
        "pluie",
        "forte pluie",
        "orage",
        "inondation",
        "inondations",
        "mauvais temps",
        "neige",
        "vent fort",
        "route bloquée",
        "route bloquee",
        "route fermée",
        "route fermee",

        # Tunisian Arabic / Arabizi
        "chta",
        "cheta",
        "cḥéta",
        "matar",
        "matar barcha",
        "matar 9wi",
        "matar 9awi",
        "rih",
        "ri7",
        "ri7 9wiya",
        "rih 9wiya",
        "ri7 9awia",
        "3ajja",
        "ajja",
        "storm",
        "sila",
        "siyel",
        "fayadan",
        "fayadhan",
        "feydhane",
        "el bhar fayed",
        "tri9 masdouda",
        "tri9 msakra",
        "tri9 msakra bel matar",
        "twaggef et-tri9",
        "et-tri9 wa9fa",
        "et-tri9 msakra",
        "talj",
        "bard barcha",
        "s9i3",
        "s9i3 barcha",
        "dhoch",
        "dhoch barcha",

        # Tunisian Arabic script
        "شتا",
        "شتى",
        "مطر",
        "مطر برشة",
        "مطر قوي",
        "ريح",
        "ريح قوية",
        "عجاج",
        "سيل",
        "سيول",
        "فيضان",
        "الطريق مسدودة",
        "الطريق مسكّرة",
        "الطريق واقفة",
        "الطريق مسكّرة بالمطر",
        "ثلج",
        "برد برشة",
        "صقيع",
    ),

    Category.ROAD_TRAFFIC: (
        # English -- construction/roadworks, congestion, strike, accident-ahead, police roadblock.
        # Deliberately does NOT include a bare "road closed"/"road blocked" phrase: that phrase is
        # already a WEATHER keyword (roads get blocked by rain too) and the two are only
        # distinguishable by what's causing the block, not the "blocked" word itself.
        "road closed for construction",
        "closed for construction",
        "construction site",
        "roadworks",
        "road works",
        "long detour",
        "detour",
        "traffic jam",
        "massive traffic jam",
        "heavy traffic",
        "not moving",
        "gridlock",
        "drivers strike",
        "truckers strike",
        "strike",
        "accident ahead",
        "accident up ahead",
        "road blocked by accident",
        "police checkpoint",
        "police roadblock",
        "blocked the road for an inspection",
        "road inspection",

        # French commonly used in Tunisia
        "route fermee travaux",
        "route fermée travaux",
        "travaux",
        "chantier",
        "grosse deviation",
        "embouteillage",
        "embouteillage enorme",
        "bouchon",
        "grand bouchon",
        "greve des routiers",
        "grève des routiers",
        "greve",
        "grève",
        "accident devant",
        "barrage de police",
        "controle de police",
        "contrôle de police",

        # Tunisian Arabic / Arabizi
        "chantier fi tri9",
        "tri9 masdouda 7asb chantier",
        "tri9 masdouda bel chantier",
        "zdi7am",
        "zdiham",
        "zdi7am kbir",
        "7adhr accident",
        "hadhr accident",
        "accident 9dami",
        "accident qdami",
        "police wa9fa fi tri9",
        "fama greve",
        "greve des routiers",

        # Tunisian Arabic script
        "أشغال",
        "الطريق مسدودة بسبب أشغال",
        "ازدحام",
        "ازدحام كبير",
        "إضراب",
        "إضراب السائقين",
        "حادث قدامي",
        "بوليس سكر الطريق",
        "حاجز بوليس",
    ),

    Category.CARGO_ISSUE: (
        # English -- missing goods, damaged/wet goods, wrong items loaded.
        "goods missing",
        "goods missing from the shipment",
        "missing items",
        "missing from the shipment",
        "couldnt find the products",
        "cant find the products",
        "products missing",
        "cargo damaged",
        "cargo is damaged",
        "items broken",
        "some items broken",
        "box arrived damaged",
        "wet cargo",
        "water damaged",
        "wrong items loaded",
        "wrong products loaded",

        # French commonly used in Tunisia
        "marchandise manquante",
        "colis endommage",
        "colis endommagé",
        "articles manquants",
        "produits manquants",
        "produits differents",
        "produits différents",
        "carton mouille",
        "carton mouillé",

        # Tunisian Arabic / Arabizi
        "ma l9itch el sel3a",
        "mal9itch el sel3a",
        "sel3a mkassra",
        "sel3a 5asra",
        "sel3a khasra",
        "el sel3a na9sa",
        "carton mballel",
        "el carton mballel",
        "package kayen probleme",
        "articles na9sin",

        # Tunisian Arabic script
        "السلعة",
        "السلعة مكسورة",
        "السلعة خسرانة",
        "الكرتون مبلل",
        "سلعة ناقصة",
        "بضاعة ناقصة",
    ),

    Category.DRIVER_ISSUE: (
        # English -- driver sick, driver injured, driver fatigued. Distinct from VEHICLE_ISSUE:
        # these are about the driver's own body/state, not the truck.
        "driver sick",
        "feel very sick",
        "feel sick",
        "cannot continue driving",
        "driver injured",
        "injured in a minor fall",
        "injured in a fall",
        "injured",
        "needs medical help",
        "besoin d une ambulance",
        "extremely tired",
        "need a short break",
        "need a break before continuing",

        # French commonly used in Tunisia
        "je suis malade",
        "malade je ne peux pas continuer",
        "chauffeur blesse",
        "chauffeur blessé",
        "chaufeur blesse",
        "blesse",
        "blessé",
        "besoin d'une ambulance",

        # Tunisian Arabic / Arabizi
        "ena mrid",
        "ena mrid barcha",
        "manjamch nkamel",
        "chaufeur jri7",
        "jri7t chwaya",
        "jri7",
        "jriha",
        "ena 3ayyen",
        "ena 3ayyen barcha",
        "lezemni nrtah",

        # Tunisian Arabic script
        "أنا مريض",
        "ما نجمش نكمل",
        "جريح",
        "جريت شوية",
        "أنا عيان",
        "لازمني نرتاح",
    ),
}


HIGH_SEVERITY_KEYWORDS = (
    # English
    "urgent",
    "delayed",
    "delay",
    "blocked",
    "major",
    "serious",
    "late",
    "very late",
    "long delay",
    "cannot continue",
    "unable to deliver",

    # French
    "urgent",
    "retard",
    "en retard",
    "gros retard",
    "bloqué",
    "bloque",
    "grave",
    "problème sérieux",
    "probleme serieux",
    "livraison impossible",

    # Tunisian Arabic / Arabizi
    "ta5ir",
    "ta5ir barcha",
    "t5ir",
    "mte5er",
    "mte5ra",
    "mesta3jel",
    "mousta3jel",
    "mosta3jel",
    "3ajel",
    "3ajla",
    "mouch normal",
    "moch normal",
    "mochkla kbira",
    "mochkel kbira",
    "mochkla kbir",
    "ma najamch nkamel",
    "ma najamch nousel",
    "ma najamtch nsallem",
    "wa9ef",
    "msakker",
    "msakra",
    "blocked",
    "kol chay wa9ef",

    # Tunisian Arabic script
    "تأخير",
    "متأخر",
    "متأخرة",
    "تأخير برشة",
    "مستعجل",
    "عاجل",
    "عاجلة",
    "مشكلة كبيرة",
    "موش عادي",
    "ما نجمش نكمل",
    "ما نجمتش نسلم",
    "واقف",
    "مسكّر",
    "مسكّرة",
)


CRITICAL_SEVERITY_KEYWORDS = (
    # English
    "critical",
    "emergency",
    "injury",
    "injured",
    "danger",
    "dangerous",
    "severe",
    "total loss",
    "life threatening",
    "medical emergency",
    "called the police",
    "police called",
    "ambulance",

    # French
    "critique",
    "urgence",
    "blessé",
    "blesse",
    "blessure",
    "danger",
    "dangereux",
    "grave",
    "perte totale",
    "appelé la police",
    "ambulance",

    # Tunisian Arabic / Arabizi
    "5atir",
    "5atira",
    "jri7",
    "jriha",
    "jraya",
    "isaba",
    "issaba",
    "7adeth",
    "7adtha",
    "7adeth kbira",
    "accident kbira",
    "mochkla 5atira",
    "mouchkla 5atira",
    "khatra",
    "khatar",
    "faza3a",
    "faza3",
    "mousta3jla barcha",
    "taleb ambulance",
    "taleb police",
    "dam",
    "yodrob fil dam",
    "ma yeta7ammelch",

    # Tunisian Arabic script
    "خطر",
    "خطيرة",
    "جريح",
    "جريحة",
    "إصابة",
    "حادث",
    "حادثة",
    "حادث كبير",
    "حادث خطير",
    "مشكلة خطيرة",
    "طارئ",
    "حالة طارئة",
    "إسعاف",
    "طلب البوليس",
    "دم",
)
